Ajout de page demande de stage detaillee
AEC-Frontend/projet-synthese pull request #11
Opened 2023-03-26 18:03 UTC by Monsieur-Luis

Ajout de la page demande de stage détaillée.

2023-03-26 18:21 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +        <h4>Kevin Labonté</h4>
Il me semble qu'il faut suivre la numérotation des titre (h1,h2,h3,h4, etc...), donc ici h2.
Et pour avoir le rendu que tu veux, tu peux ajouter une class à ton h2.

2023-03-26 18:58 UTC, SanaG1002 reviewed
Allo Luis, juste pour info, j'ai fait des commentaires pour te dire moi comment je l'aurai fait, je ne suis absolument experte.
Tu verra qu'il y a beaucoup de répétition dans mes commentaires.

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +      <img src="assets/close.svg" />
- Les images sont bien, mais des icones seraient plus appropriées ? Mathieu à précisé, que ce n'était pas grave si ce n'était pas exactement les mêmes.
- Sauf erreurs de ma part, les icones devraient être cliquable.

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +        </p>
Au lieux d'avoir 2 balises <p>, peux être n'en mettre qu'une et ajouter un <br> pour sauter une ligne.
ex: 
<p> Lorem ................................................. <br> Lorem..................................................................</p>

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div>
Le div ici ne sert à rien, il faut le retirer.

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div style="margin-right: 30%">
Mettre le style dans le fichier CSS est une meilleure pratique.

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div>
Retirer le div

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div style="margin-right: 30%">
Style à mettre dans le fichier CSS

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div>
Retirer div

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div style="margin-right: 30%">
Style dans le fichier CSS

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +              <h1>Développeur Front-End</h1>
Pour toute les données, comme on a pas d'API, je suppose que tu à mis les mêmes infos partout, mais peut être mettre les vrais nom de titre, comme ils seront sur le même modèle: 
- Programme de formation
- Secteur d'activité
- Compétences
- Établissement d'enseignement 
- Ville
- Région

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div>
div à retirer

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +              <h1>Développeur Front-End</h1>
Pour toute les données, comme on a pas d'API, je suppose que tu à mis les mêmes infos partout, mais peut être mettre les vrais nom de titre, comme ils seront sur le même modèle: 

- Type de stage
- Nombre d'heure par semaine
- Rémunération
- Date de début
- Date de fin

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div style="margin-right: 30%">
Mettre style dans fichier CSS

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div>
div à retirer

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div style="margin-right: 30%">
Style dans CSS

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +          <div>
div à retirer

2023-03-26 18:58 UTC, SanaG1002 commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +      </mat-card>
Il me semble que le </mat-card> est de trop.

2023-03-26 21:47 UTC, jonathan-nadeau requested changes

2023-03-26 21:47 UTC, jonathan-nadeau commented on src/app/app.component.html
>  <router-outlet></router-outlet>
`router-outlet` doit être à l'intérieur de `app-sidenav`

2023-03-26 21:47 UTC, jonathan-nadeau commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +    <div class="icons">
Même commentaire que @SanaG1002 . Les icons devraient être des boutons et il faudrait que ça soit des icons à l'intérieur des boutons. Les boutons `ajout` et `édition` devraient renvoyer vers `demandes-de-stage/ajout` et `demandes-de-stage/:id/edition`

2023-03-26 21:47 UTC, jonathan-nadeau commented on src/app/pages/demandes-de-stage-page/demandes-de-stage-page.component.html
> +        <h4>Kevin Labonté</h4>
On pourrait perdre des points ici si la hiérarchie des titres ne sont pas respectée.

2023-03-26 21:47 UTC, jonathan-nadeau commented
Cette page ne devrait pas être au endpoint `demandes-de-stage` mais au endpoint `demandes-de-stage/:id`

2023-03-31 00:35 UTC, SanaG1002 approved these changes

2023-03-31 00:56 UTC, SanaG1002 approved these changes

2023-03-31 03:24 UTC, SanaG1002 approved these changes

2023-03-31 06:00 UTC, jonathan-nadeau approved these changes

2023-03-31 06:02 UTC, merged