ajout de offre de stage detaillee
AEC-Frontend/projet-synthese pull request #18
Opened 2023-04-01 01:55 UTC by Monsieur-Luis

2023-04-01 17:23 UTC, jonathan-nadeau requested changes
Ne pas oublier de régler les conflits également!

2023-04-01 17:23 UTC, jonathan-nadeau commented on src/app/offre-de-stage-detaillee/offre-de-stage-detaillee.component.html
> +    </div>
Comme on travaille avec le `RouterModule` d'Angular, il est important d'utilisant ce module pour naviguer à travers l'application et non de renvoyer l'utilisateur vers une nouvelle page web. Et pour ce qui est du `close-icon`, est-ce qu'il n'est pas supposé supprimer l'offre de stage? Si c'est le cas, c'est mieux d'utiliser un `button`.

 ```suggestion
    <div class="icons">
      <a routerLink=""><mat-icon class="check-icon">check</mat-icon></a>
      <a routerLink=""><mat-icon class="edit-icon">edit</mat-icon></a>
      <button type="button" (click)="deleteOffreDeStage()"><mat-icon class="close-icon">close</mat-icon></button>
    </div>
```

2023-04-02 18:54 UTC, Monsieur-Luis commented on src/app/offre-de-stage-detaillee/offre-de-stage-detaillee.component.html
> +    </div>
Allo, je vais ajouter le bouton et les fonctionnalités dans la PSA 20 Offre de stage détaillé / Fonctionnalités

2023-04-02 19:00 UTC, SanaG1002 approved these changes

2023-04-07 13:54 UTC, jonathan-nadeau approved these changes

2023-04-07 13:54 UTC, merged